### ISSUE TITLE
Improve Mobile Responsiveness of Website

### ISSUE THREAD

**Issue by SandeepVashishtha** [SandeepVashishtha/Wanna-Date#14]
## Description
The website is not fully responsive on mobile devices. Some elements are not resizing properly, leading to a poor user experience on smaller screens.

## Steps to Reproduce
1. Open the website on a mobile device or in a mobile view in the browser's developer tools.
2. Notice that some elements are not resizing properly.

## Expected Behavior
The website should be fully responsive and provide a good user experience on all screen sizes.

## Actual Behavior
Some elements are not resizing properly on smaller screens.

## Possible Solution
Implement CSS media queries to adjust the styling for different screen sizes.

**Comment by dhruv465** [comment]
I can help you with mobile responsiveness

**Comment by SandeepVashishtha** [comment]
> I can help you with mobile responsiveness 

Create a pull request for resolution

**Comment by dhruv465** [comment]
Hey, the branch has been updated, so feel free to merge it now.
